baseURL = "https://www.jeroentrimbach.com/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
# Title left top corner
title = "Jeroen Trimbach"
# Change the default theme to be use when building the site with Hugo
theme = "uBlogger"

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
# enableGitInfo = true
# whether to use emoji code
# enableEmoji = true

# website images for open graph and twitter cards
#images = ["/logo.png"]

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 4
  # [[menu.main]]
  #   identifier = "linkedin"
  #   pre = "<i class='fab fa-linkedin'></i>"
  #   post = ""
  #   name = ""
  #   url = "https://linkedin.com/in/jeroen-trimbach/"
  #   title = "LinkedIn"
  #   weight = 5

[params]
    # uBlogger theme version
    version = "2.0.X"
    # site default theme ("light", "dark", "auto")
    # defaultTheme = "auto"
    # public git repo url only then enableGitInfo is true
    # gitRepo = "https://github.com/upagge/dolboblog-theme"
    # which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
    fingerprint = ""
    # date format
    dateFormat = "02-01-2006"
    # website images for Open Graph and Twitter Cards
    # images = ["/images/banner.png"]
    # logo
    # logo = ["/images/banner.png"]
    # site description
    description = "beep boop I'm backing up.. 🤖" # will appear when you share link
    # site keywords
    keywords = ["Theme", "Hugo", "Tech", "SQL", "DBA", "Azure", "DevOps", "Engineer", "Cloud", "Blog", "CV", "PowerShell"]
      # Search config
      [params.search]
        enable = true
        # type of search engine ("lunr", "algolia")
        type = "lunr"
        # max index length of the chunked content
        contentLength = 4000
        # placeholder of the search bar
        placeholder = ""
        # max number of results length
        maxResultLength = 10
        # snippet length of the result
        snippetLength = 30
        # HTML tag name of the highlight part in results
        highlightTag = "em"
        # whether to use the absolute URL based on the baseURL in search index
        absoluteURL = false
        # [search.algolia]
        #   index = "index"
        #   appID = "PASDMWALPK"
        #   searchKey = "b42948e51daaa93df92381c8e2ac0f93"
      # Home page config
      [params.home]
        # amount of RSS pages
        rss = 10
        # Home page profile
        [params.home.profile]
          enable = true
          # Gravatar Email for preferred avatar in home page
          gravatarEmail = "jeroen.trimbach@gmail.com"
          # URL of avatar shown in home page
          avatarURL = "" #"/images/avatar.png"
          # title shown in home page (HTML format is supported)
          title = "My Blog Thing 😎"
          # subtitle shown in home page (HTML format is supported)
          subtitle = "A Work In Progress.. "
          # whether to show social links
          social = true
          # disclaimer (HTML format is supported)
          disclaimer = ""
        # Home page posts
        [params.home.posts]
          enable = true
          # special amount of posts in each home posts page
          paginate = 6
      # Social config in home page
      [params.social]
        GitHub = "jeroen-t"
        Linkedin = "jeroen-trimbach/"
        RSS = true
    # Header config
      [params.header]
        # desktop header mode ("fixed", "normal", "auto")
        # desktopMode = "fixed"
        # mobile header mode ("fixed", "normal", "auto")
        # mobileMode = "auto"
        # Header title config
        [params.header.title]
            # URL of the LOGO
            # logo = ""
            # title name
            name = "Jeroen Trimbach"
            # you can add extra information before the name (HTML format is supported), such as icons
            # pre = "<i class='fas fa-pencil-alt fa-fw'></i>"
            # you can add extra information after the name (HTML format is supported), such as icons
            # post = ""
        # Footer config
        [params.footer]
            enable = true
            # Custom content (HTML format is supported)
            custom = 'Hosted on GitHub'
            # whether to show Hugo and theme info
            hugo = true
            # whether to show copyright info
            copyright = true
            # whether to show the author
            # 是否显示作者
            author = true
            # site creation time
            since = 2021
            # ICP info only in China (HTML format is supported)
            # icp = ""
            # license info (HTML format is supported)
            license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
        # Section (all posts) page config
        # uBlogger NEW | 0.2.0 App icon config
        [params.app]
          # optional site title override for the app when added to an iOS home screen or Android launcher
          title = "jTrimbach"
          # whether to omit favicon resource links
          noFavicon = false
          #favicon = "images/favico.ico"
          # # modern SVG favicon to use in place of older style .png and .ico files
          #svgFavicon = "favicon.svg"
          # # Android browser theme color
          # themeColor = "#007fff"
          # # Safari mask icon color
          # iconColor = "#007fff"
          # # Windows v8-10 tile color
          #  tileColor = "#007fff"
        [params.section]
            # special amount of posts in each section page
            paginate = 20
            # date format (month and day)
            dateFormat = "02-01"
            # amount of RSS pages
            rss = 10
        # List (category or tag) page config
        [params.list]
            # special amount of posts in each list page
            paginate = 20
            # date format (month and day)
            dateFormat = "02-01"
            # amount of RSS pages
            rss = 10
        # # Comment config
        [params.comment]
             enable = true
        #     [params.comment.remark42]
        #     enable = true
        #     host = "https://comments.upagge.ru"
        #     site = "documentation"
        #     locale = "en"
        #     # Disqus comment config (https://disqus.com/)
        #     [params.comment.disqus]
        #     enable = false
        #     # Disqus shortname to use Disqus in posts
        #     shortname = ""
        #     # Gitalk comment config (https://github.com/gitalk/gitalk)
              # [params.comment.gitalk]
              # enable = true
              # owner = "jeroen-t"
              # repo = "https://github.com/jeroen-t/gitalkcomments.git"
              # clientId = "af13e32b9a2ab81c4025"
              # clientSecret = "7693161c2a17eb678008c5dd525abd3bcd2f8f72"
            # Valine comment config (https://github.com/xCss/Valine)
            # [params.comment.valine]
            # enable = false
            # appId = "QGzwQXOqs5JOhN4RGPOkR2mR-MdYXbMMI"
            # appKey = "WBmoGyJtbqUswvfLh6L8iEBr"
            # placeholder = ""
            # avatar = "mp"
            # meta= ""
            # pageSize = 10
            # lang = ""
            # visitor = true
            # recordIP = true
            # highlight = true
            # enableQQ = false
            # serverURLs = "https://"
            # # emoji data file name, default is "google.yml"
            # # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
            # # located in "themes/uBlogger/assets/data/emoji/" directory
            # # you can store your own data files in the same path under your project:
            # # "assets/data/emoji/"
            # emoji = ""
        #     # Facebook comment config (https://developers.facebook.com/docs/plugins/comments)
        #     [params.comment.facebook]
        #     enable = false
        #     width = "100%"
        #     numPosts = 10
        #     appId = ""
        #     languageCode = ""
        #     # Telegram comments config (https://comments.app/)
        #     [params.comment.telegram]
        #     enable = false
        #     siteID = ""
        #     limit = 5
        #     height = ""
        #     color = ""
        #     colorful = true
        #     dislikes = false
        #     outlined = false
        #     # Commento comment config (https://commento.io/)
        #     [params.comment.commento]
        #     enable = false
        #     # Utterances comment config (https://utteranc.es/)
            [params.comment.utterances]
            enable = true
            # owner/repo
            repo = "jeroen-t/utterances-comments"
            issueTerm = "pathname"
            label = "comment"
            lightTheme = "github-light"
            darkTheme = "github-dark"
        # Page config
        # 文章页面配置
        [params.page]
            # whether to hide a page from home page
            hiddenFromHomePage = false
            # whether to hide a page from search results
            hiddenFromSearch = false
            # whether to enable twemoji
            twemoji = false
            # whether to enable the ruby extended syntax
            ruby = true
            # whether to enable the fraction extended syntax
            fraction = true
            # whether to enable the fontawesome extended syntax
            fontawesome = true
            # whether to show link to Raw Markdown content of the content
            linkToMarkdown = true
            # whether to show the full text content in RSS
            rssFullText = false
            # Table of the contents config
            [params.page.toc]
            # whether to enable the table of the contents
            enable = true
            # whether to keep the static table of the contents in front of the post
            keepStatic = false
            # whether to make the table of the contents in the sidebar automatically collapsed
            auto = true
            # Code config
            [params.page.code]
            # whether to show the copy button of the code block
            copy = true
            # the maximum number of lines of displayed code by default
            maxShownLines = 10
            # KaTeX mathematical formulas config (KaTeX https://katex.org/)
            [params.page.math]
            enable = false
            # default block delimiter is $$ ... $$ and \\[ ... \\]
            blockLeftDelimiter = ""
            blockRightDelimiter = ""
            # default inline delimiter is $ ... $ and \\( ... \\)
            inlineLeftDelimiter = ""
            inlineRightDelimiter = ""
            # KaTeX extension copy_tex
            copyTex = true
            # KaTeX extension mhchem
            mhchem = true
            # Mapbox GL JS config (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
            [params.page.mapbox]
            # access token of Mapbox GL JS
            accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
            # style for the light theme
            lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
            # style for the dark theme
            darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
            # whether to add NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
            navigation = true
            # whether to add GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
            geolocate = true
            # whether to add ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
            scale = true
            # whether to add FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
            fullscreen = true
            # Social share links in post page
            [params.page.share]
            enable = true
            Twitter = true
            Facebook = true
            Linkedin = true
            Whatsapp = true
            Pinterest = false
            Tumblr = false
            # HackerNews = true
            Reddit = true
            # Third-party library config
            # [params.page.library]
            # [params.page.library.css]
            #     # someCSS = "some.css"
            #     # located in "assets/"
            #     # someCSS = "https://cdn.example.com/some.css"
            # [params.page.library.js]
            #     # someJavascript = "some.js"
            #     # located in "assets/"
            #     # someJavascript = "https://cdn.example.com/some.js"
            # # Page SEO config
            # [params.page.seo]
            # # image URL
            # images = []
            # # Publisher info
            # [params.page.seo.publisher]
            #     name = "xxxx"
            #     logoUrl = "/images/avatar.png"
        # Site verification code for Google/Bing/Yandex/Pinterest/Baidu
        [params.verification]
            google = "G-NZDT366YND"
            # bing = ""
            # yandex = ""
            # pinterest = ""
            # baidu = ""

        # Site SEO config
        # [params.seo]
        #     # image URL
        #     image = "/images/Apple-Devices-Preview.png"
        #     # thumbnail URL
        #     thumbnailUrl = "/images/screenshot.png"

        # Analytics config
        [params.analytics]
            enable = true
            # Google Analytics
            [params.analytics.google]
                # [UA-XXXXXXXX-X] google analytics code
                id = "276260495"
                # whether to use gtag linked
                gtag = true
                # whether to anonymize IP
                anonymizeIP = true
            # Fathom Analytics
            # [params.analytics.fathom]
            #     id = ""
            #     # server url for your tracker if you're self hosting
            #     server = ""
            # [params.analytics.yandex]
            #     id = "70532758"

        # # Cookie consent config
        # [params.cookieconsent]
        # enable = false
            # # text strings used for Cookie consent banner
            # [params.cookieconsent.content]
            #     message = ""
            #     dismiss = ""
            #     link = ""

        # # CDN config for third-party library files
        # [params.cdn]
        # # CDN data file name, disabled by default
        # # ("jsdelivr.yml")
        # # located in "themes/uBlogger/assets/data/cdn/" directory
        # # you can store your own data files in the same path under your project:
        # # "assets/data/cdn/"
        # data = "jsdelivr.yml"

        # Compatibility config
        [params.compatibility]
        # whether to use Polyfill.io to be compatible with older browsers
        polyfill = false
        # whether to use object-fit-images to be compatible with older browsers
        objectFit = false


# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
  #Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author config
#  [author]
#    name = "jeroen"

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config (https://gohugo.io/content-management/urls/#permalinks)
 [Permalinks]
   # posts = ":year/:month/:filename"
   posts = ":year/:month/:filename"

# Privacy config (https://gohugo.io/about/hugo-and-gdpr/)
# [privacy]
#   # privacy of the Google Analytics (replaced by params.analytics.google)
#   [privacy.googleAnalytics]
#     # ...
#   [privacy.twitter]
#     enableDNT = true
#   [privacy.youtube]
#     privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/html"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]